### ISSUE TITLE
Add example for property that returns generators

### ISSUE THREAD

**Issue by erny** [sphinx-contrib/napoleon#23]
It's said that properties docstrings should return type such as:
```python
    @property
    def title(self):
        """str: document title"""
        return self._title
```
On the other hand, generators should use "Yields":
```python
    def get_children(self):
        """Gets any contained elements

        Yields:
            Element: next contained document
        """
        for element in self._find_elements(parent=self.id):
            yield element
```
But how do we specify properties that return generators? Would this be correct?:
```python
    @property
    def children(self):
        """:obj:`generator` of :obj:`Document`: contained elements"""
        for element in self._find_elements(parent=self.id):
            yield element
```

**Comment by McSinyx** [comment]
Hi, please note that this repo is deprecated.  To answer to your question, by PEP 484, iterators should be typed as `typing.Iterator[Document]`.  `typing.Generator` also exists but it has some extra functionalities.

**Comment by erny** [comment]
Thanks, I'll close this issue.
