### ISSUE TITLE
Archival

### ISSUE THREAD

**Issue by AA-Turner** [sphinx-contrib/napoleon#43]
@dhellmann please archive this repository, users should be redirected to https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html.

A

**Comment by dhellmann** [comment]
@AA-Turner , @RobRuana is the admin for this repo.

**Comment by twmr** [comment]
@RobRuana friendly ping.

**Comment by RobRuana** [comment]
Yep, this repo needs to be archived!

So long, and thanks for all the fish!
