### ISSUE TITLE
Documentation: Adds user defined custom sections

### ISSUE THREAD

**Issue by sobolevn** [sphinx-contrib/napoleon#5]
Hi, thanks for this tool and the recent update.

I am wondering what does the following mean: "Adds user defined custom sections".
I am highly interested in this feature, but I am unable to find any documentation about how that should work.

Could you please guide me, so I can write the proper docs for this feature?
Or maybe I am just missing something.

**Comment by RobRuana** [comment]
Apologies, the docs were not automatically updated with the newest release. There is a small section describing the `napoleon_custom_sections` here:

https://sphinxcontrib-napoleon.readthedocs.io/en/latest/sphinxcontrib.napoleon.html#sphinxcontrib.napoleon.Config.napoleon_custom_sections

You add that setting in your `conf.py`.
